Repository ProjectKinni/kkini-backend, pull requests merged in 2023-09, with the labels that each got.

#12 [KN-140] Review CRUD 기능 추가
  src/main/java/com/example/kinnibackend/controller/review/ReviewController.java
  src/main/java/com/example/kinnibackend/dto/review/CreateReviewRequestDTO.java
  src/main/java/com/example/kinnibackend/dto/review/CreateReviewResponseDTO.java
  src/main/java/com/example/kinnibackend/dto/review/DeleteReviewResponseDTO.java
  src/main/java/com/example/kinnibackend/dto/review/GetReviewResponseDTO.java
  src/main/java/com/example/kinnibackend/dto/review/UpdateReviewResponseDTO.java
  src/main/java/com/example/kinnibackend/entity/Review.java
  src/main/java/com/example/kinnibackend/repository/review/ReviewRepository.java
  src/main/java/com/example/kinnibackend/service/review/ReviewService.java
  src/main/resources/application.yml
  src/test/java/com/example/kinnibackend/review/ReviewControllerTest.java
  src/test/java/com/example/kinnibackend/review/ReviewRepositoryTest.java
  src/test/java/com/example/kinnibackend/review/ReviewServiceTest.java
Labels: enhancement

#14 [KN-139] ProductFilteringService 코드 수정
  src/main/java/com/example/kinnibackend/config/WebOAuthSecurityConfig.java
  src/main/java/com/example/kinnibackend/service/productFiltering/ProductFilteringService.java
Labels: bug

#15 [KN-175] 검색 기능 수정
  src/main/java/com/example/kinnibackend/dto/product/ProductCardListResponseDTO.java
  src/main/java/com/example/kinnibackend/exception/search/handler/GlobalExceptionHandler.java
  src/main/java/com/example/kinnibackend/repository/product/ProductRepository.java
  src/main/java/com/example/kinnibackend/service/productFiltering/ProductFilteringService.java
  src/main/java/com/example/kinnibackend/service/search/SearchService.java
  src/test/java/com/example/kinnibackend/product/ProductRepositoryTest.java
  src/test/java/com/example/kinnibackend/searchAndFiltering/ProductFilteringServiceTest.java
  src/test/java/com/example/kinnibackend/searchAndFiltering/SearchServiceTest.java
Labels: fix

#17 Deployment
  src/main/java/com/example/kinnibackend/config/WebOAuthSecurityConfig.java
  src/main/java/com/example/kinnibackend/config/oauth/OAuth2SuccessHandler.java
  src/main/java/com/example/kinnibackend/config/oauth/OAuth2UserCustomService.java
  src/main/java/com/example/kinnibackend/controller/category/CategoryController.java
  src/main/java/com/example/kinnibackend/controller/review/ReviewController.java
  src/main/java/com/example/kinnibackend/controller/search/SearchController.java
  src/main/java/com/example/kinnibackend/controller/searchAndFiltering/SearchAndFilteringController.java
  src/main/java/com/example/kinnibackend/controller/user/UserController.java
  src/main/java/com/example/kinnibackend/dto/product/ProductCardListResponseDTO.java
  src/main/java/com/example/kinnibackend/dto/product/ProductMainCardResponseDTO.java
  src/main/java/com/example/kinnibackend/dto/review/CreateReviewRequestDTO.java
  src/main/java/com/example/kinnibackend/dto/review/CreateReviewResponseDTO.java
  src/main/java/com/example/kinnibackend/dto/review/DeleteReviewResponseDTO.java
  src/main/java/com/example/kinnibackend/dto/review/GetReviewResponseDTO.java
  src/main/java/com/example/kinnibackend/dto/review/UpdateReviewResponseDTO.java
  src/main/java/com/example/kinnibackend/dto/user/GetUserInfoDTO.java
  src/main/java/com/example/kinnibackend/dto/user/UserUpdateDTO.java
  src/main/java/com/example/kinnibackend/entity/Product.java
  src/main/java/com/example/kinnibackend/entity/Review.java
  src/main/java/com/example/kinnibackend/entity/Users.java
  src/main/java/com/example/kinnibackend/exception/search/handler/GlobalExceptionHandler.java
  src/main/java/com/example/kinnibackend/repository/product/ProductRepository.java
  src/main/java/com/example/kinnibackend/repository/review/ReviewRepository.java
  src/main/java/com/example/kinnibackend/repository/token/RefreshTokenRepository.java
  src/main/java/com/example/kinnibackend/repository/user/UserRepository.java
  src/main/java/com/example/kinnibackend/service/category/CategoryService.java
  src/main/java/com/example/kinnibackend/service/filtering/FilteringService.java
  src/main/java/com/example/kinnibackend/service/productFiltering/ProductFilteringService.java
  src/main/java/com/example/kinnibackend/service/review/ReviewService.java
  src/main/java/com/example/kinnibackend/service/search/SearchService.java
  src/main/java/com/example/kinnibackend/service/token/RefreshTokenService.java
  src/main/java/com/example/kinnibackend/service/user/UserService.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/test/java/com/example/kinnibackend/category/CategoryControllerTest.java
  src/test/java/com/example/kinnibackend/category/CategoryServiceTest.java
  src/test/java/com/example/kinnibackend/product/ProductRepositoryTest.java
  src/test/java/com/example/kinnibackend/productAndFiltering/SearchAndFilteringControllerTest.java
  src/test/java/com/example/kinnibackend/review/ReviewControllerTest.java
  src/test/java/com/example/kinnibackend/review/ReviewRepositoryTest.java
  src/test/java/com/example/kinnibackend/review/ReviewServiceTest.java
  src/test/java/com/example/kinnibackend/search/SearchControllerTest.java
  src/test/java/com/example/kinnibackend/search/SearchServiceTest.java
  src/test/java/com/example/kinnibackend/searchAndFiltering/ProductFilteringServiceTest.java
  src/test/java/com/example/kinnibackend/searchAndFiltering/SearchServiceTest.java
  src/test/java/com/example/kinnibackend/token/RefreshTokenServiceTest.java
  src/test/java/com/example/kinnibackend/token/TokenApiControllerTest.java
  src/test/java/com/example/kinnibackend/token/jwt/TokenProviderTest.java
  src/test/java/com/example/kinnibackend/user/UserControllerTest.java
  src/test/java/com/example/kinnibackend/user/UsersServiceTest.java
Labels: merge

#18 Deployment
  Dockerfile
  build.gradle
  src/main/java/com/example/kinnibackend/config/JasyptConfigAES.java
  src/main/resources/application-db.yml
  src/main/resources/application-jwt.yml
  src/main/resources/application-oauth2.yml
  src/test/java/com/example/kinnibackend/example/TestRepositoryTests.java
  src/test/java/com/example/kinnibackend/review/ReviewRepositoryTest.java
  src/test/java/com/example/kinnibackend/token/RefreshTokenServiceTest.java
  src/test/java/com/example/kinnibackend/token/TokenApiControllerTest.java
  src/test/java/com/example/kinnibackend/token/jwt/TokenProviderTest.java
  src/test/java/com/example/kinnibackend/user/UserControllerTest.java
  src/test/java/com/example/kinnibackend/user/UsersServiceTest.java
Labels: merge

#19 Deployment
  Dockerfile
  build.gradle
  src/main/java/com/example/kinnibackend/config/JasyptConfigAES.java
  src/main/resources/application-db.yml
  src/main/resources/application-jwt.yml
  src/main/resources/application-oauth2.yml
  src/test/java/com/example/kinnibackend/example/TestRepositoryTests.java
  src/test/java/com/example/kinnibackend/review/ReviewRepositoryTest.java
  src/test/java/com/example/kinnibackend/token/RefreshTokenServiceTest.java
  src/test/java/com/example/kinnibackend/token/TokenApiControllerTest.java
  src/test/java/com/example/kinnibackend/token/jwt/TokenProviderTest.java
  src/test/java/com/example/kinnibackend/user/UserControllerTest.java
  src/test/java/com/example/kinnibackend/user/UsersServiceTest.java
Labels: merge

#21 [KN-194] 평점 평균 로직 구현
  src/main/java/com/example/kinnibackend/controller/review/ReviewController.java
  src/main/java/com/example/kinnibackend/controller/searchAndFiltering/SearchAndFilteringController.java
  src/main/java/com/example/kinnibackend/dto/product/ProductFilteringResponseDTO.java
  src/main/java/com/example/kinnibackend/entity/Product.java
  src/main/java/com/example/kinnibackend/repository/product/ProductRepository.java
  src/main/java/com/example/kinnibackend/repository/review/ReviewRepository.java
  src/main/java/com/example/kinnibackend/service/product/ProductService.java
  src/main/java/com/example/kinnibackend/service/productFiltering/ProductFilteringService.java
  src/main/java/com/example/kinnibackend/service/review/ReviewService.java
  src/main/java/com/example/kinnibackend/service/search/SearchService.java
  src/test/java/com/example/kinnibackend/searchAndFiltering/ProductFilteringServiceTest.java
  src/test/java/com/example/kinnibackend/searchAndFiltering/SearchServiceTest.java
Labels: feat

#22 [KN-195] feat: ProductLike
  src/main/java/com/example/kinnibackend/controller/productLike/ProductLikeController.java
  src/main/java/com/example/kinnibackend/dto/productLike/ProductLikeDTO.java
  src/main/java/com/example/kinnibackend/entity/Like/LikeId.java
  src/main/java/com/example/kinnibackend/entity/Like/ProductLike.java
  src/main/java/com/example/kinnibackend/entity/Users.java
  src/main/java/com/example/kinnibackend/repository/productLike/ProductLikeRepository.java
  src/main/java/com/example/kinnibackend/service/productLike/ProductLikeService.java
  src/test/java/com/example/kinnibackend/productLike/ProductLikeServiceTest.java
Labels: feat

#23 [KN-198] 조회수 구현 완료
  src/main/java/com/example/kinnibackend/controller/productLike/ProductLikeController.java
  src/main/java/com/example/kinnibackend/controller/searchAndFiltering/SearchAndFilteringController.java
  src/main/java/com/example/kinnibackend/dto/product/ProductCardListResponseDTO.java
  src/main/java/com/example/kinnibackend/entity/Users.java
  src/main/java/com/example/kinnibackend/entity/like/LikeId.java
  src/main/java/com/example/kinnibackend/entity/like/ProductLike.java
  src/main/java/com/example/kinnibackend/entity/productViewCount/ProductViewCount.java
  src/main/java/com/example/kinnibackend/entity/productViewCount/ProductViewCountId.java
  src/main/java/com/example/kinnibackend/repository/product/ProductRepository.java
  src/main/java/com/example/kinnibackend/repository/product/ProductViewCountRepository.java
  src/main/java/com/example/kinnibackend/repository/productLike/ProductLikeRepository.java
  src/main/java/com/example/kinnibackend/service/product/ProductFilteringService.java
  src/main/java/com/example/kinnibackend/service/productLike/ProductLikeService.java
  src/main/java/com/example/kinnibackend/service/search/SearchService.java
  src/test/java/com/example/kinnibackend/searchAndFiltering/ProductFilteringServiceTest.java
Labels: feat

#26 [KN-197] feat: MyPage ReviewList
  src/main/java/com/example/kinnibackend/controller/review/ReviewController.java
  src/main/java/com/example/kinnibackend/repository/review/ReviewRepository.java
  src/main/java/com/example/kinnibackend/service/review/ReviewService.java
Labels: feat

#28 [KN-201] 추천 로직 재구성
  src/main/java/com/example/kinnibackend/controller/product/ProductController.java
  src/main/java/com/example/kinnibackend/dto/product/ProductCardListResponseDTO.java
  src/main/java/com/example/kinnibackend/dto/product/ProductFilterResponseDTO.java
  src/main/java/com/example/kinnibackend/dto/product/ProductFilteringResponseDTO.java
  src/main/java/com/example/kinnibackend/dto/product/ProductMainCardResponseDTO.java
  src/main/java/com/example/kinnibackend/entity/Product.java
  src/main/java/com/example/kinnibackend/entity/ProductFilter.java
  src/main/java/com/example/kinnibackend/repository/product/ProductFilterRepository.java
  src/main/java/com/example/kinnibackend/repository/product/ProductRepository.java
  src/main/java/com/example/kinnibackend/service/product/ProductFilterService.java
  src/test/java/com/example/kinnibackend/searchAndFiltering/ProductFilterServiceTest.java
Labels: feat

#30 [KN-196] Review 사진 업로드, ReviewCount 표시
  build.gradle
  src/main/java/com/example/kinnibackend/controller/review/ReviewController.java
  src/main/java/com/example/kinnibackend/controller/searchAndFiltering/SearchAndFilteringController.java
  src/main/java/com/example/kinnibackend/dto/product/ProductCardListResponseDTO.java
  src/main/java/com/example/kinnibackend/dto/review/CreateReviewRequestDTO.java
  src/main/java/com/example/kinnibackend/entity/Review.java
  src/main/java/com/example/kinnibackend/repository/review/ReviewRepository.java
  src/main/java/com/example/kinnibackend/service/product/ProductFilteringService.java
  src/main/java/com/example/kinnibackend/service/review/ReviewService.java
  src/main/java/com/example/kinnibackend/service/search/SearchService.java
  src/main/java/com/example/kinnibackend/utils/objectstorage/S3Client.java
  src/main/resources/application-s3.yml
  src/main/resources/application.yml
Labels: feat

#32 [KN-196] Add Infinite Scroll
  src/main/java/com/example/kinnibackend/controller/searchAndFiltering/SearchAndFilteringController.java
  src/main/java/com/example/kinnibackend/repository/product/ProductRepository.java
  src/main/java/com/example/kinnibackend/service/product/ProductFilteringService.java
  src/test/java/com/example/kinnibackend/product/ProductRepositoryTest.java
  src/test/java/com/example/kinnibackend/searchAndFiltering/ProductFilterServiceTest.java
Labels: feat

#34 fix: User delete
  src/main/java/com/example/kinnibackend/repository/product/ProductViewCountRepository.java
  src/main/java/com/example/kinnibackend/repository/productLike/ProductLikeRepository.java
  src/main/java/com/example/kinnibackend/repository/review/ReviewRepository.java
  src/main/java/com/example/kinnibackend/service/user/UserService.java
Labels: fix

#39 [Kn 226] - 페이징 처리 추가
  src/main/java/com/example/kinnibackend/controller/product/ProductController.java
  src/main/java/com/example/kinnibackend/repository/product/ProductFilterRepository.java
  src/main/java/com/example/kinnibackend/repository/product/ProductRepository.java
  src/main/java/com/example/kinnibackend/service/product/ProductFilterService.java
Labels: feat
